### ISSUE TITLE
Some Limine files are not copied to .zigmod directory

### ISSUE THREAD

**Issue by jackdbd** [ominitay/zigvale-barebones#1]
It seems that a couple of Limine files are not copied to the expected location.

I tried to compile the kernel with `zig build iso` and I got this error:

```sh
FATAL: Limine binary .zigmod/deps/v/git/github.com/limine-bootloader/limine/branch-latest-binary/limine-eltorito-efi.bin doesn't exist
```

I have the zigmod binary at `~/bin/zigmod`

Since I had previously followed the [original Stivale Bare Bones guide](https://wiki.osdev.org/Stivale_Bare_Bones), I had already the necessary `limine-eltorito-efi.bin` file, so I simply copied it and pasted it to `~/repos/zigvale-barebones/.zigmod/deps/v/git/github.com/limine-bootloader/limine/branch-latest-binary/limine-cd-efi.bin`

Then I re-tried `zig build iso` and I got another similar error:

```sh
FATAL: Limine binary .zigmod/deps/v/git/github.com/limine-bootloader/limine/branch-latest-binary/limine-install-linux-x86_64 doesn't exist
```

Again, I simply copied and pasted `limine-install-linux-x86_64` to `~/repos/zigvale-barebones/.zigmod/deps/v/git/github.com/limine-bootloader/limine/branch-latest-binary/limine-install-linux-x86_64`

This fixed the issue and I was able to compile the kernel and launch the example with:

```sh
zig build iso
qemu-system-x86_64 -cdrom ./zig-out/iso/zigvale-barebones.iso -m 128M
```

Maybe the files were not copied because I was supposed to place the zigmod binary in this example's root directory?

my OS: Ubuntu 20.04.4 LTS x86_64

**Comment by ominitay** [comment]
oh god more breaking changes from limine
i'll fix this in a moment

**Comment by ominitay** [comment]
limine changed git history, breaking our lockfile. i assume you deleted the lockfile after seeing `zigmod fetch` fail, which will have merged in breaking changes. mint doesn't want to rewrite history again to fix this (which is fair enough), so i've switched the branch to a v2.0-only branch, which shouldn't break again.

**Comment by jackdbd** [comment]
I don't remember if I deleted the lockfile. Sorry, it was the first time I tried zigmod.

**Comment by ominitay** [comment]
Nope probably not. I found out that there's currently a footgun with Zigmod in which it doesn't obey the lockfile when using `zigmod fetch`, only when using `zigmod ci`. I'll update the readme to reflect this, although Zigmod will be changed to fix this in the future iirc.
